### PR TITLE
Updated email regex

### PR DESCRIPTION
**Pull request by Ekultek**
Updated the email regex to be a little more accurate

Example:

```
>>> emails = ["almira_eckl@mail.com", "por.bop@msn.com", "trinit_eckley@myspace.com", "fifranc@freewebmail.com"]
>>> def validate_email(email):
        import re
        valid = re.compile(r"^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$")
        if valid.match(email):
		print "yes"
	else: print "No"

	
>>> for item in emails:
	validate_email(item)

	
yes
yes
yes
yes
>>> 
```

### CODE REVIEW

**Comment by kronolynx** [comment]
The proposed regex would fail for ICANN-era and Internationalized country TLD

https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#ICANN-era_generic_top-level_domains

**Comment by Ekultek** [comment]
Which extension in particular are you referring to?

**Comment by Ekultek** [comment]
Did some testing:

```
>>> def validate_email_1(email):
	import re
	valid = re.compile(r"^[^@]+@[^@]+\.[^@]+$")
	if valid.match(email):
		print "Validation method 1 matched"
	else:
		print "Validation method 1 failed"

		
>>> def validate_email_2(email):
	import re
	valid = re.compile(r"^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$")
	if valid.match(email):
		print "Validation method 2 matched"
	else:
		print "Validation method 2 failed"

		
>>> emails = ["almira_eckl@mail.com", "por.bop@msn.com", "trinit_eckley@myspace.com", "fifranc@freewebmail.com", "test@test.academy", "test@test.accountant", "test@test.accountants"]
>>> for item in emails:
	validate_email_1(item)
	validate_email_2(item)

	
Validation method 1 matched
Validation method 2 matched
Validation method 1 matched
Validation method 2 matched
Validation method 1 matched
Validation method 2 matched
Validation method 1 matched
Validation method 2 matched
Validation method 1 matched
Validation method 2 failed
Validation method 1 matched
Validation method 2 failed
Validation method 1 matched
Validation method 2 failed
```

On that note, closing the pull request down

**Comment by aesedepece** [comment]
Hi @Ekultek
First of all, thanks a lot for your PR! It makes us specially happy to see people contributing!
Please feel free to update this PR or open another with a regex that take into account the aforementioned TLDs.

**Comment by Ekultek** [comment]
@aesedepece Will do I'll figure one out, thanks

**Pull request closed without merging**
